### ISSUE TITLE
error with <sessions-enabled>true</sessions-enabled>

### ISSUE THREAD

**Issue by ludoch** [ludoch/appengine-spring-boot#2]
GCLOUD: INFO: Local Datastore initialized: 
GCLOUD: 	Type: High Replication
GCLOUD: 	Storage: /Users/ludo/ee10/spring/appengine-spring-boot/target/appengine-spring-boot-1.0.0-SNAPSHOT/WEB-INF/appengine-generated/local_db.bin
GCLOUD: Oct 20, 2023 2:00:34 PM com.google.appengine.api.datastore.dev.LocalDatastoreService load
GCLOUD: INFO: The backing store, /Users/ludo/ee10/spring/appengine-spring-boot/target/appengine-spring-boot-1.0.0-SNAPSHOT/WEB-INF/appengine-generated/local_db.bin, does not exist. It will be created.
GCLOUD: 2023-10-20 14:00:35.289:WARN :oejes.ServletChannel:qtp1276504061-154: unknown request
GCLOUD: java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.server.Request.getAttribute(String)" because "request" is null
GCLOUD: 	at org.eclipse.jetty.server.Request.getAuthenticationState(Request.java:912)
GCLOUD: 	at org.eclipse.jetty.security.AuthenticationState.getAuthenticationState(AuthenticationState.java:45)
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.ServletApiRequest.getAuthentication(ServletApiRequest.java:128)
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.ServletApiRequest.getUndeferredAuthentication(ServletApiRequest.java:133)
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.ServletApiRequest.getUserPrincipal(ServletApiRequest.java:345)
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.ServletApiRequest.getRemoteUser(ServletApiRequest.java:324)
GCLOUD: 	at com.google.appengine.tools.development.jetty.ee10.JettyContainerService.onComplete(JettyContainerService.java:702)
GCLOUD: 	at com.google.appengine.tools.development.jetty.ee10.JettyContainerService$ApiProxyHandler.lambda$handle$0(JettyContainerService.java:636)
GCLOUD: 	at org.eclipse.jetty.util.Callback$5.completed(Callback.java:242)
GCLOUD: 	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:420)
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.ServletChannel.onCompleted(ServletChannel.java:823)
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:481)
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:463)
GCLOUD: 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:571)
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:693)
GCLOUD: 	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:713)
GCLOUD: 	at com.google.appengine.tools.development.jetty.ee10.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:637)
GCLOUD: 	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:812)
GCLOUD: 	at org.eclipse.jetty.server.Server.handle(Server.java:177)
GCLOUD: 	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:649)
GCLOUD: 	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:471)
GCLOUD: 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
GCLOUD: 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
GCLOUD: 	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
GCLOUD: 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:971)
GCLOUD: 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1196)
GCLOUD: 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1151)
GCLOUD: 	at java.base/java.lang.Thread.run(Thread.java:833)
GCLOUD: 2023-10-20 14:00:35.293:WARN :oejs.Response:qtp1276504061-154: writeError: status=500, message=java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.ee10.servlet.ServletContextResponse.isCommitted()" because the return value of "org.eclipse.jetty.ee10.servlet.ServletChannel.getServletContextResponse()" is null, response=org.eclipse.jetty.ee10.servlet.ServletContextResponse@7b7b393b
GCLOUD: java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.ee10.servlet.ServletContextResponse.isCommitted()" because the return value of "org.eclipse.jetty.ee10.servlet.ServletChannel.getServletContextResponse()" is null
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.ServletChannelState.isResponseCommitted(ServletChannelState.java:311)
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.ServletChannel.isCommitted(ServletChannel.java:834)
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.ServletChannel.handleException(ServletChannel.java:716)
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:641)
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:463)
GCLOUD: 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:571)
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:693)
GCLOUD: 	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:713)
GCLOUD: 	at com.google.appengine.tools.development.jetty.ee10.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:637)
GCLOUD: 	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:812)
GCLOUD: 	at org.eclipse.jetty.server.Server.handle(Server.java:177)
GCLOUD: 	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:649)
GCLOUD: 	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:471)
GCLOUD: 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
GCLOUD: 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
GCLOUD: 	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
GCLOUD: 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:971)
GCLOUD: 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1196)
GCLOUD: 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1151)
GCLOUD: 	at java.base/java.lang.Thread.run(Thread.java:833)
GCLOUD: Oct 20, 2023 2:01:04 PM com.google.appengine.api.datastore.dev.LocalDatastoreService$11 run
GCLOUD: INFO: Time to persist datastore: 12 ms

**Comment by ludoch** [comment]
Seems to be fixed
