### ISSUE TITLE
Error with committed response on local devappserver

### ISSUE THREAD

**Issue by ludoch** [ludoch/appengine-spring-boot#4]

**Comment by ludoch** [comment]
With mvn install appengine:run, Access the main page, after a while see this error:

GCLOUD: Mar 25, 2024 1:02:57 PM org.springframework.boot.web.servlet.support.ErrorPageFilter handleCommittedResponse
GCLOUD: SEVERE: Cannot forward to error page for request [/favicon.ico] as the response has already been committed. As a result, the response may have the wrong status code. If your application is running on WebSphere Application Server you may be able to resolve this problem by setting com.ibm.ws.webcontainer.invokeFlushAfterService to false
GCLOUD: org.eclipse.jetty.io.EofException: Closed
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.HttpOutput.checkWritable(HttpOutput.java:686)
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.HttpOutput.write(HttpOutput.java:716)
GCLOUD: 	at java.base/java.io.OutputStream.write(OutputStream.java:124)
GCLOUD: 	at org.springframework.security.web.util.OnCommittedResponseWrapper$SaveContextServletOutputStream.write(OnCommittedResponseWrapper.java:633)
GCLOUD: 	at com.google.appengine.tools.development.ee10.ResponseRewriterFilter$ResponseWrapper.reallyCommit(ResponseRewriterFilter.java:873)
GCLOUD: 	at com.google.appengine.tools.development.ee10.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:172)
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
GCLOUD: 	at com.google.appengine.tools.development.ee10.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:46)
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
GCLOUD: 	at com.google.appengine.api.blobstore.dev.ee10.ServeBlobFilter.doFilter(ServeBlobFilter.java:78)
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
GCLOUD: 	at com.google.apphosting.utils.servlet.ee10.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:62)
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
GCLOUD: 	at com.google.appengine.tools.development.jetty.ee10.StaticFileFilter.doFilter(StaticFileFilter.java:143)
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
GCLOUD: 	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
GCLOUD: 	at com.google.appengine.tools.development.ee10.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:322)
GCLOUD: 	at com.google.appengine.tools.development.ee10.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:305)
GCLOUD: 	at com.google.appengine.tools.development.ee10.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:109)

**Comment by ludoch** [comment]
@lachlan-roberts
